### ISSUE TITLE
Quiet Mode

### ISSUE THREAD

**Issue by ManiMatter** [TandonArchit/SongNameSplit#1]
Hi,

would it be possible to add a flag that runs SongNameSplit quietly, i.e. without printing to the terminal?
Instead, it should raise an error if it encounters problems.

Pseudo Code:
```
try:
    result = SongNameSplit.namesplit(MySongName, quiet=true)
except ValueError as error:
    # Handle error 
    print('An Error occurred: ' + error)
```

The advantage of this is that I can steer whether I want to print or not (and change the behavior for instance depening on whether i run on DEBUG mode, etc)

**Comment by TandonArchit** [comment]
I have released a new version of the library with a "runQuietly" flag. You can use it like this:

`SongNameSplit.namesplit("<< SONG TITLE >>", runQuietly=True)`

Make sure to update the library to its latest release. As for the errors, the library already raises proper errors if it encounters any issues, so that has no changes.

**Comment by ManiMatter** [comment]
Thank you very much
